plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'info.picocli:picocli-spring-boot-starter:4.7.5'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

bootJar {
    archiveFileName = 'brain-cli.jar'
    mainClass = 'com.secondbrain.cli.BrainCli'
}
