package com.secondbrain.common.enums;

public enum EventType {
    SESSION_STARTED,
    TASK_STARTED,
    PLAN_CREATED,
    FILE_READ,
    FILE_CREATED,
    FILE_MODIFIED,
    FILE_DELETED,
    COMMAND_EXECUTED,
    TEST_EXECUTED,
    TEST_FAILED,
    TEST_PASSED,
    BUILD_STARTED,
    BUILD_FAILED,
    BUILD_SUCCEEDED,
    GIT_COMMIT,
    GIT_PUSH,
    DECISION_MADE,
    PROBLEM_DISCOVERED,
    SOLUTION_FOUND,
    TASK_COMPLETED,
    TASK_BLOCKED,
    SESSION_ENDED
}
